# fly.toml app configuration file generated for frontend-silent-darkness-7145 on 2024-09-13T00:06:25+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brandcraft'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[env]
  VITE_BACKEND_URL = "https://backend-dry-sea-3601.fly.dev"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1